<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MyGuestBook.aspx.cs" Inherits="ASPDemo.MyGuestBook" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1
        {
            width: 100%;
        }
        .auto-style2
        {
            width: 250px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <h3>Leave a Message in our GuestBook</h3>
        <table class="auto-style1">
            <tr>
                <td class="auto-style2">Name</td>
                <td>
                    <asp:TextBox ID="txbName" runat="server" Width="300px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">E-Mail</td>
                <td>
                    <asp:TextBox ID="txbEmail" runat="server" Width="300px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">Tel the World</td>
                <td>
                    <asp:TextBox ID="txbComment" runat="server" Height="100px" TextMode="MultiLine" Width="300px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">
                    <asp:Button ID="btnSubmit" runat="server" Height="26px" OnClick="btnSubmit_Click" Text="Submit" Width="157px" />
                </td>
                <td>
                    <asp:Button ID="btnClear" runat="server" Text="Clear" Width="142px" OnClick="btnClear_Click" />
                </td>
            </tr>
        </table>
    
    </div>
        <p>
            &nbsp;</p>
        <p>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="MessageID" DataSourceID="sdsMessages">
                <Columns>
                    <asp:BoundField DataField="MessageID" HeaderText="MessageID" InsertVisible="False" ReadOnly="True" SortExpression="MessageID" />
                    <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                    <asp:BoundField DataField="Message" HeaderText="Message" SortExpression="Message" />
                </Columns>
            </asp:GridView>
        </p>
        <p>
            <asp:SqlDataSource ID="sdsMessages" runat="server" ConnectionString="<%$ ConnectionStrings:GuestBookConnectionString %>"
                DeleteCommand="DELETE FROM [Messages] WHERE [MessageID] = @MessageID" 
                InsertCommand="INSERT INTO [Messages] ([Date], [Name], [Email], [Message]) 
                VALUES (convert(varchar, CURRENT_TIMESTAMP, 101), @Name, @Email, @Message)" 
                SelectCommand="SELECT * FROM [Messages]" 
                UpdateCommand="UPDATE [Messages] SET [Date] = @Date, [Name] = @Name, [Email] 
                = @Email, [Message] = @Message WHERE [MessageID] = @MessageID">
                <DeleteParameters>
                    <asp:Parameter Name="MessageID" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:FormParameter Name="Name" FormField="txbName" Type="String" />
                    <asp:FormParameter Name="Email" FormField="txbEmail" Type="String" />
                    <asp:FormParameter Name="Message" FormField ="txbComment" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Date" Type="String" />
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Message" Type="String" />
                    <asp:Parameter Name="MessageID" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </p>
        <asp:Label ID="lblError" runat="server"></asp:Label>
    </form>
</body>
</html>
