//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimesP6
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_fields
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string band { get; set; }
        public string season { get; set; }
        public string yesno { get; set; }
        public string colors { get; set; }
        public string matter { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
